export type MeterDBDTO = {
  meterId: string;
  meterSerialNo: string;
  moduleNo: string;
  encryptionKey: string;
  phaseTypeValue: "single" | "threePhase" | "ht" | "ct" | "ltct";
  phaseTypeDescription: "Single" | "Three Phase" | "HT" | "CT" | "LTCT";
  sourceTypeValue: "single" | "dual";
  sourceTypeDescription: "Single" | "Dual";
  consumptionTypeValue: "gas" | "energy" | "water" | "other";
  consumptionTypeDescription: "Gas" | "Energy" | "Water" | "Other";
  projectId: string;
  projectName: string;
  consumerId: string;
  consumerName: string;
  firmwareVersion: string;
  consumption_type: string;
  cumulative_vah_genset: string;
  cumulative_vah_grid: string;
  cumulative_wh_genset: string;
  cumulative_wh_grid: string;
  dg_enable_disable: string;
  energy_source_id: string;
  grid_enable_disable: string;
  master_cutoff_status: string;
  md_kva_dg_current_mth: string;
  md_kva_grid_current_mth: string;
  md_kw_dg_current_mth: string;
  md_kw_grid_current_mth: string;
  meter_consumption: string;
  meter_balance_dg: string;
  meter_balance_grid: string;
  meter_s_no: string;
  overload_status: string;
  overload_threshold_for_dg: string;
  overload_threshold_for_grid: string;
  power_factor: string;
  push_interval_in_minute: string;
  total_active_power: string;
  total_apparent_power: string;
};
