export default {
    "rows": [
        {
            "userId": "Diganta",
            "accountTypeValue": "superAdmin",
            "accountTypeDescription": "Super Admin",
            "accessLevel": 1,
            "changePasswordToken": "NO_TOKEN",
            "email": "ray.diganta00@gmail.com",
            "firstName": "Diganta",
            "lastName": "Ray",
            "userName": "Diganta",
            "mobileNo": "7042472125",
            "password": "password",
            "projectId": "",
            "projectName": "",
            "enabled": true,
            "description":"test"
        },
        {
            "userId": "Jaya",
            "accountTypeValue": "admin",
            "accountTypeDescription": "Admin",
            "accessLevel": 2,
            "changePasswordToken": "NO_TOKEN",
            "email": "jaya.gusain27@gmail.com",
            "firstName": "Jaya",
            "lastName": "Singh",
            "userName": "Jaya",
            "mobileNo": "7042472126",
            "password": "password",
            "projectId": "project_1",
            "projectName": "Vasundhara",
            "enabled": true
        },
        {
            "userId": "Jaideep",
            "accountTypeValue": "accountManager",
            "accountTypeDescription": "Account Mngr.",
            "accessLevel": 3,
            "changePasswordToken": "NO_TOKEN",
            "email": "jaideep@gmail.com",
            "firstName": "Jaideep",
            "lastName": "Yala",
            "userName": "Jaideep",
            "mobileNo": "7042472126",
            "password": "password",
            "projectId": "project_1",
            "projectName": "Vasundhara",
            "enabled": true
        },
        {
            "userId": "Vandana",
            "accountTypeValue": "admin",
            "accountTypeDescription": "Admin",
            "accessLevel": 2,
            "changePasswordToken": "NO_TOKEN",
            "email": "vandana@gmail.com",
            "firstName": "Vandana",
            "lastName": "Gusain",
            "userName": "Vandana",
            "mobileNo": "7042472127",
            "password": "password",
            "projectId": "project_2",
            "projectName": "Vardhaman",
            "enabled": true
        },
        {
            "userId": "Harsh",
            "accountTypeValue": "admin",
            "accountTypeDescription": "Admin",
            "accessLevel": 2,
            "changePasswordToken": "NO_TOKEN",
            "email": "harshit@gmail.com",
            "firstName": "Harsh",
            "lastName": "Joshi",
            "userName": "Harsh",
            "mobileNo": "7042472128",
            "password": "password",
            "projectId": "project_3",
            "projectName": "Noida Sector-18",
            "enabled": true
        },
        {
            "userId": "Harshit",
            "accountTypeValue": "vendingManager",
            "accountTypeDescription": "Vending Mngr.",
            "accessLevel": 3,
            "changePasswordToken": "NO_TOKEN",
            "email": "harsh@gmail.com",
            "firstName": "Harshit",
            "lastName": "Srivastava",
            "userName": "Harshit",
            "mobileNo": "7042472129",
            "password": "password",
            "projectId": "project_1",
            "projectName": "Vasundhara",
            "enabled": false
        }
    ]
}